### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by llh721113** [HMUniversity/About#128]
Dear whom may concern,
Hello. I want to join Home University to lie flat!
By the way, in the real life, I'm in the University of Chinese Academy of Science, UCAS for short as well.

Regards,
llh721113

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
