### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by hmsjy2017** [HMUniversity/About#129]
Dear whom may concern,
Hello. I want to join Home University to lie flat!

Regards,
hmsjy2017

**Comment by manoil** [comment]
Dear whom may concern,
Hello. I want to join Home University to lie flat!

Best,
Oilman

**Comment by KevinZonda** [comment]
Hi @manoil and @hmsjy2017 ,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
