### ISSUE TITLE
Apply issue

### ISSUE THREAD

**Issue by manoil** [HMUniversity/About#134]
Dear whom may concern,

Hello. I want to join Home University. But unfortunately, I did not receive an email after my application being accepted.
Could you please reinvite me again?

Regards,
Oilman

**Comment by AkinoKaede** [comment]
Hi @manoil ,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
