### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by StickTech** [HMUniversity/About#135]
Dear whom may concern,

  Hello. This is Stick Tech, a former member of NHK (Higigomori Institution of Japan).
  I found HM University via some of my friends, and after some extra research, I found HM University is the university that fits my needs. I truly believe the idea of reducing the involution and enhancing the ability simultaneously is what I always wanted.

  Thus, I am here to apply to this university. 

Best regards,
StickTech

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
