### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by wfly1998** [HMUniversity/About#140]
Dear whom may concern,
Hello. I want to join Home University to lie flat!

Regards,
@wfly1998

**Comment by AkinoKaede** [comment]
Dear Mr./Ms./Mx.,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University

**Comment by wfly1998** [comment]
@KevinZonda Excuse me, I am an alumnus of HMU. I noticed that new colleges has built after I admitted to HMU. I want to know that can I join them and how to join them? Thanks.
