### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by mnixry** [HMUniversity/About#161]
Dear whom may concern,

After a thorough research about different colleges, the Home University is my final choice. This university offers a `Lyingology `(also known as 躺平学) program and has an outstanding reputation and excellent reviews. Home University is a recommendation by the previous graduates and I am interested in enrolling myself in the Lyingology program.

My aim is to finish the Lyingology program offered at the Home University and I want to continue my studies after graduating from the undergraduate program. After entering the graduate program I want to become a counselor dealing with young children.

Majors in Lyingology is my long-term goal and I am confident of making the right career choice. Attached is my application, transcripts, essays, and letters of recommendation as per the admission requirement.

I look forward to hearing from you soon.

Sincerely,
mnixry

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University

**Comment by KevinZonda** [comment]
Attention, our uni locates in GB, so you have to accept British spelling, e.g. you should replace program by programme, college by university. 
Wish you enjoy lessons and every success with your future plans. :)
