### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by zhiwei-Feng** [HMUniversity/About#163]
Dear whom may concern,
Hello. I want to join Home University to lie flat!
I am lying flat in such a beautiful position that you cannot refuse my application！😝😝

Regards,
zhiwei-Feng

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
