### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by OxfordStreet** [HMUniversity/About#189]
Dear whom may concern,
Hello. 
I want to join Home University to lie flat!
I just finished my undergraduate life, and I hope to make progress together with you in the next year of preparing for the postgraduate entrance examination.
Looking forward to your reply.

Regards,
<YourID>

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
