### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by XiGou** [HMUniversity/About#192]
Dear Sir, 
  I don't have a bachelor degree and master degree from Tsinghua University;
  I don't have a IELTS transscript;
  I never won a scholarship from school;
  I am not good at science, math and languages;
  The only thing I know is my ignorance;
  The only thing I successfully accompolished is to be a loser;
  
  My confidence drove me to apply for HMU, hope you can approve!

Sencerely,
Me

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
