### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by cncherisher** [HMUniversity/About#199]
Dear whom may concern,
Hello. I want to join Home University to lie flat!

I just finished my undergraduate life, and I hope to make progress together with you in the year of preparing for the postgraduate entrance examination.
Looking forward to your reply.

Regards,
<@cncherisher>

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
