### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by SkipM4** [HMUniversity/About#238]
Dear whom may concern,
Hello. I want to join Home University to lie flat!

Regards,
SkipM4

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University

**Comment by SkipM4** [comment]
> Hi,
> Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.
> 
> Regards,
> Home University

Thanks.

**Comment by KevinZonda** [comment]
> > Hi,
> > Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.
> > Regards,
> > Home University
> 
> Thanks.

Don't worry :)
