### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by SummerSec** [HMUniversity/About#246]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
清水

**Comment by SummerSec** [comment]
Dear whom may concern,
Hello. I want to join Home University to lie flat!

Regards

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
