### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by SaigyoujiYuyuko233** [HMUniversity/About#27]
Dear whom may concern,
Hello. I hate the f\*\*king god damn involution and I don't wanna take the f\*\*king SAT so I apply.

Regards,
SaigyoujiYuyuko233

**Comment by KevinZonda** [comment]
Hi @SaigyoujiYuyuko233,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
