### ISSUE TITLE
卧龙诸葛申请入学！

### ISSUE THREAD

**Issue by SleepingDragonZhuge** [HMUniversity/About#279]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！  拥护校规校纪，坚决反对内卷！卧龙诸葛绝不会和邓艾打起来！
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
你的名字

**Comment by SleepingDragonZhuge** [comment]
我的名字：卧龙诸葛
笑）

**Comment by KevinZonda** [comment]
Isn't Zhuge pig pigeons?

**Comment by Zhengfourth** [comment]
SleepingDragonPigPigeons

**Comment by cw1997** [comment]
**來者可是諸葛孔明**

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
