### ISSUE TITLE
yplpA

### ISSUE THREAD

**Issue by MCUmbrella** [HMUniversity/About#282]
omnc cn aDyrm,hoaew   er
yl noflooo  vjiti!naalwii s e .temenU eo IHrH tttl

,re saR dg
bMraeUlmlC

**Comment by KevinZonda** [comment]
Dear Mx. MCUmbrella,
Unfortunately your qualifications do not meet the current requirements for admission to this area. There are limited places in each of our programmes and the number of applications we receive far exceeds the number of places. Admission is granted on a competitive basis.

We appreciate your interest and wish you every success with your future plans.

Regards,
Home University

**Comment by 8MiYile** [comment]
wdnmd 你他妈是不是把内容打散了再发的啊

**Comment by MCUmbrella** [comment]
> wdnmd 你他妈是不是把内容打散了再发的啊

[要不然你觉得会是什么呢😋](https://github.com/MCUmbrella/wtfusayin)

**Comment by KevinZonda** [comment]
It's nonsense that use classic cryptography to tricky others. This is a pointless, disappointing and egregious act which only can waste project maintainers' time. Shame on you.

**Comment by MCUmbrella** [comment]
![lh3 googleusercontent com_1606042729](https://user-images.githubusercontent.com/40854260/125170259-b45f4b00-e1e0-11eb-88da-fe073d560025.jpg)

**Comment by KevinZonda** [comment]
Mention again, confusing others is **NOT** a good behaviour.
