### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by PhoebeCLS** [HMUniversity/About#290]
Dear Sir,

My name is PhoebeCLS in China senior high school, I am writing in the hope that I may obtain an opportunity to further my study in your university.

This year in the summer,I will graduate and get my degree.I plan to continue my study and research in this field.I got a lot of honors in school.My English level is not only in the forefront of the age, and the results of all subjects are very excellent(**Up to 1 point**).I have the good quality of being willing to help others,I can communicate and cooperate with classmates fluently,have a strong interest in academic research.The reason why I choose Home university is that the learning _**dun**_ and **_tangpin_** there is good.It can provide _excellent_ knowledge resources and communicate with talents from all over the world.And my solid academic background will meet your general entrance requirements for graduate study.

I will appreciate it very much if you could send me the Graduate Application Forms,the Application Form for Scholarships/Assistantships,and other relevant information.My mailing address is shown on the top of this letter.

I am looking forward to hearing from you soon.

Sincerely，

PhoebeCLS

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
