### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by YukiChiyoda** [HMUniversity/About#291]
Dear Principal of HMU,
Hello. I want to join Home University.
I'm sorry for not noticing the first mail so I miss the first offer. Now I just want to lie flat!! =w=

Regards,
YukiChiyoda

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
