### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by LLLgoyour** [HMUniversity/About#311]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！  
我志愿在家里蹲大学躺着成为RBQ，用不同的语言表达RBQ的需求！（大雾
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
Shinonome

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
