### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by AmagiDDmxh** [HMUniversity/About#313]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
AmagiDDmxh

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University

**Comment by AmagiDDmxh** [comment]
时效只有 7 天吗？一直没注意邮箱...突然间就没了，我应该再发一次申请书吗？ 😂

**Comment by KevinZonda** [comment]
Done.

20 Aug 2021, 18:23 by ***@***.***:
