### ISSUE TITLE
申请入学家里蹲大学

### ISSUE THREAD

**Issue by Johnserf-Seed** [HMUniversity/About#315]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！  
借此增加一份新的海外留学文凭（jia de），望校方可以通过我的入学申请。
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
JohnserfSeed

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
