### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by 1574242600** [HMUniversity/About#318]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
Nworm

**Comment by MaxChang3** [comment]
欢迎加入
(不好意思点错了:(

**Comment by 1574242600** [comment]
没事，我正愁邮箱太过冷清，都没人舍得给我发条spam

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
