### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by EnergyMaking** [HMUniversity/About#322]
家里蹲大学：  
您好！我志愿加入家里蹲大学躺平！  
我是个愚蠢的人。但我觉得那还不够。我还想变得更慢、更矮、更弱。
此致  
敬礼  
你的名字

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
