### ISSUE TITLE
申请教育邮箱

### ISSUE THREAD

**Issue by jingwangnet** [HMUniversity/About#324]
家里蹲大学校长：
        您好！我是家里蹲大学的莘莘学子，想申请个教育邮箱 jingwangnet@home.8mi.edu.pl
        此致
敬礼
jingwangnet

**Comment by LiHua-Official** [comment]
啊这，这能用 “莘莘学子” ？

**Comment by jingwangnet** [comment]
这不是重点！ 我作为家里蹲大学的学员 申请个 邮箱 不过份吧！ 谢谢各位校长

**Comment by KevinZonda** [comment]
@8MiYile

**Comment by 8MiYile** [comment]
稍等 我恢复一下 我以为没人用 就暂停了 等我一下

**Comment by 8MiYile** [comment]
https://cpanel.8mi.tech/invitation?user=jingwangnet@home.8mi.edu.pl&cookie=43d2XwaVLam1vrL6

**Comment by jingwangnet** [comment]
老哥 这个邮箱配置貌似有点问题？ Gmail 和 腾讯企业邮 QQ 都不能收信

发自我的iPhone

**Comment by 8MiYile** [comment]
@jingwangnet 我有在找问题到底出在哪个环节了 因为admin@8mi.edu.pl是可以发送且无回退的 估计是DNS刷新那块

**Comment by jingwangnet** [comment]
> @jingwangnet 我有在找问题到底出在哪个环节了 因为[admin@8mi.edu.pl](mailto:admin@8mi.edu.pl)是可以发送且无回退的 估计是DNS刷新那块
目前我可以正常接收邮件 放送邮件有些问题

**Comment by 8MiYile** [comment]
@jingwangnet 接收肯定是正常的 接收只看SPF和MX记录正确就行 但是发送还要验证DKIM和DMARC内容可用性

**Comment by jingwangnet** [comment]
修好了吗 老哥？

发自我的iPhone

**Comment by 8MiYile** [comment]
@jingwangnet 或许修好了 不过还没验证。。您那边可以试着发送一下

**Comment by jingwangnet** [comment]
腾讯企业邮 测试 不行

发自我的iPhone

**Comment by 8MiYile** [comment]
@jingwangnet 分配了个新邮箱 在你自己项目的issues内

**Comment by jingwangnet** [comment]
新邮箱 我测试了 下 依然不可以


发自我的iPhone

**Comment by 8MiYile** [comment]
完蛋 IP list 草了

**Comment by 8MiYile** [comment]
等待我们迁移服务器并拿到各大网站的认证吧 真烦人（嘤嘤嘤）

**Comment by jingwangnet** [comment]
辛苦了


发自我的iPhone
