### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by keta1** [HMUniversity/About#338]
Dear whom may concern,  
Hello. I want to join Home University to lie flat!

Regards,  
<keta1>

**Comment by KevinZonda** [comment]
@ChungZH Prof. ZHU

**Comment by clang-with-gcc** [comment]
Hi,
🎉 Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Prof. CLANG-WITH-GCC @ Home University
