### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by YukariChiba** [HMUniversity/About#342]
Dear whom may concern,  

Hello. I want to join Home University to lie flat!

As an aspiring student, I am applying for admission to your college. My research indicates that the Master in Flat-Lying program you offers is outstanding, and will provide me with the best training to enter this profession. Your organization has excellent reputation. After the exceptional reviews I received from recent students, I am convinced that this is the best college to pursue my studies in lying flat.

Regards,  
@YukariChiba

**Comment by KevinZonda** [comment]
Hi,
🎉 Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
