### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by werifu** [HMUniversity/About#346]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学！ 我对于贵校的家里蹲原理与最佳实践项目相当感兴趣，希望能在贵校深造
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
werifu

**Comment by KevinZonda** [comment]
Hi,
🎉 Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
