### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by HyperGroups** [HMUniversity/About#348]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学xxx学院躺平！

我想创造一个学院，家里蹲帝国理工学院。

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
剑域子群HyperGroups

**Comment by Cubik65536** [comment]
Hi,
🎉 Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University

**Comment by KevinZonda** [comment]
Hi,

We found the new college Imperial Canteen College which is named after Imperial College London. The new college is going to provide students' drinks and food.

See more at https://github.com/orgs/HMUniversity/teams/imperial-canteen-college

Best,
KevinZonda
