### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by cubercsl** [HMUniversity/About#35]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Dear whom may concern,
Hello. I want to join Home University to lie flat!

Regards, cubercsl.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEyMKIxXtjzdNAmHhJRcZLGekWHkEFAmDLGdYACgkQRcZLGekW
HkF/qw/+NZxt+HzScL/hp3Wp1BW6OareGHl/NVqEgw5jg5h1Mi90x1B9e2VXnM/3
e9VCb9sDkOlJ4lvgwF1TF8AgpW70fdOvzfHRSyAls3qmwnKDEQwfu9vjhReo3S4W
FgO23r4rLheY+fmnHaHfhJAnBEO9T6m7k90IMtaEre1Foqbets1m3Bd8UTy388Rg
wWK4ANkyOI3BW+vz5fTyf1dhQS6oz5JA7IAbjDPKDRf7D2YVvybdEA8v3zVj6SyV
mtG076g8U2gDYKKTo//UqkY/VSOQUJvnjqKrT+mrCb92rb9YBXjTmOJ5bZDJhRNo
y4RGpTFSoIem1EIczu5gyEjrrPcG1FnAz1PMX30qX6nQ5hedkix426KFKQbFZmcz
oppqLF6xE5hALX3OUahvN8AdqTvVsze1jnkGyUAsjoo6ZM21EOGGsOa/8MAY1cTm
6Kg+NEmvl7L8UZKUwCHJjH1V2iIBhGxkXpmHnrK3BIh9Z7+F11g10+fnhHuCQIVP
ZvTB9weIC6EJ+HQUBNM5Fr32MyKWvgMxgKzqf4sG0TfiEISvmzpa6nwlhhfvs8ZS
EvKF+mamEa+DpfMubH3nAlEsFwRxjoZqBDeEcU6okNvYLV8KFSbSRpFzAXmpsqmP
jCvWUKRctYUnsrGaQln3aDM+rz2nPNJTgUKz5WJwRZMd3K5FR78=
=xsoU
-----END PGP SIGNATURE-----

**Comment by KevinZonda** [comment]
Hi @cubercsl,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
