### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by jiangchufeng** [HMUniversity/About#363]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学计算机学院躺平！

如果你想加入一个特定学院请在此处修改：计算机学院！
如果不需要，请删除学院信息！

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
你的名字：蒋楚枫

爱你们！

**Comment by Cubik65536** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University

**Comment by Cubik65536** [comment]
您好，

我们暂时不能处理您希望进入计算机学院的申请，因为我们暂时没有设立专门的计算机学院。你可以前往此处查看学院的列表：https://github.com/HMUniversity/Colleges

此致

Cubik65536
HMU大学副主席，St. Linus学院主理
