### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by Macsara** [HMUniversity/About#377]
Dear whom may concern,  
Hello. I want to join Home University to lie flat!

Check the college if you want to join it:
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)
- [x] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)

Regards,  
Sara

**Comment by Cubik65536** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University

**Comment by Macsara** [comment]
Thanks!
