### ISSUE TITLE
申請

### ISSUE THREAD

**Issue by KusakabeShi** [HMUniversity/About#380]
家裡蹲大學：  
        您好！我志願加入家裡蹲大學， 體驗全球一流家裡蹲教育！為家裡蹲奮鬥終身！

如果你想加入一個特定學院請在此處勾選：
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)  
- [X] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)

        此致  
敬禮
Kusakabe Si

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
