### ISSUE TITLE
Application Letter

### ISSUE THREAD

**Issue by AkinoKaede** [HMUniversity/About#4]
Dear Sir or Madam,  
  Hello. I think this is the Home University is I have been looking for. And I want to join this university.  
<p align="right">Yours sincerely,
</br>AkinoKaede</p>

**Comment by KevinZonda** [comment]
Hi @AkinoKaede,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
