### ISSUE TITLE
Appliance Request

### ISSUE THREAD

**Issue by JuanCldCmt** [HMUniversity/About#44]
####  As is known to all, HMU is a very serious and cutting-edge top university, hence, it' essential to introduce myself before you consider my appliance. I am a day dreamer, not-so good Linux enthusiast, bad homework-doer, and also, I have several special personalities as listed below:
* The ability to go to bed at 10:30PM every night in order to maintain a good health and not to get bald before 50.
* The firm determination to resist involution of any kind, and possess all kinds of preparation to prepare for lying down if necessary.
* The admiration of UNIX philosophy, KISS principles and FOSS movements.
#### When it comes to my personal experience, I have made countless achievements in the following aspects:
* I have lived countless days on earth, which is a unique experience that not many people have achieved.
* I have personally experienced many important international meetings with presidents from Iceland, ROC, Japan and the US. (please note that some of my friends call themselves presidents of various countries)
* I have expertised the deep meaning of Taoism and Lao Tzu's very understandings of the world, for instance, the Tao and the Te, do nothing to achieve anything, et cetra, which has proved priceless value in modern society.

**Comment by KevinZonda** [comment]
Hi @JuanCldCmt,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
