### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by RAOE** [HMUniversity/About#457]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！

如果你想加入一个特定学院请在此处勾选：
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)
- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
徐塬峰

**Comment by Cubik65536** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University

**Comment by RAOE** [comment]
Can I re-apply, the previous email is invalid

**Comment by Cubik65536** [comment]
There's another invitation sent to your email.
