### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by RAOE** [HMUniversity/About#458]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！

如果你想加入一个特定学院请在此处勾选：
- [ ] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)
- [x] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
徐塬峰

**Comment by Cubik65536** [comment]
Hi,

If you want to join another college, submit new request at [GitHub Teams](https://github.com/orgs/HMUniversity/teams).

Regards,
Home University
