### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by StarxSky** [HMUniversity/About#479]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学内卷！
努力内卷！卷出奇迹！

如果你想加入一个特定学院请在此处勾选：
- [ ] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)
- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
StarxSky

**Comment by Cubik65536** [comment]
Dear StarxSky,

The admission committee has concluded its evaluation of your admission application. Unfortunately, we judge that you don't have the values that we ask of our students, we are unable to accept your admission application, and we are **NOT** going to accept any of your new admission letters.

The admission committee appreciates the time and effort you put into applying to Home University. We wish you every success as you pursue your education.

Sincerely,
_**Cubik65536**_
Admissions Director, Home University
