### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by XuanMiaoSama** [HMUniversity/About#492]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！以此来学习如何更加高效的躺平,本人参加过好吃懒做大赛并以二等奖成绩获得了"不如第一名"称号.我坚信贵校的教育水平能更好的令我成长,足以打败第一名获得"一等废物"限量称号.

如果你想加入一个特定学院请在此处勾选：
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)
- [x] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
Akyuu

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
