### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by VidocqH** [HMUniversity/About#5]
Hello,
I think HM University is perfect for me to 混吃等死.

Sincerely,
VidocqH

---
Btw, I think it would be better if here have an issue template. XD

**Comment by KevinZonda** [comment]
Hi @VidocqH,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Thanks for your suggest! We'll consider it!

Regards,
Home University

**Comment by KevinZonda** [comment]
Hello! Issue template has been created at ff1d796. Thanks for your support!
