### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by EnabledFish** [HMUniversity/About#534]
Dear whom may concern,  
Hello. I want to join Home University to lie flat!

Check the college if you want to join it:

- [x] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- [ ] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

Regards,  
EnabledFish

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
