### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by scyq** [HMUniversity/About#56]
Dear whom may concern,
Hello. I want to join Home University to lie flat!
I hate f**king involution and nine nine six. I want to pursue my dream in HMU and become rich.
Regards,
scyq

**Comment by KevinZonda** [comment]
Hi @scyq,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
