### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by Nofated095** [HMUniversity/About#575]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！

如果你想加入一个特定学院请在此处勾选：

- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

请注意，上述链接均已 404。

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
Nofated James

**Comment by Nofated095** [comment]
![image](https://user-images.githubusercontent.com/49985975/180372248-745e903f-0b92-443c-9257-4ee916e2341d.png)
![image](https://user-images.githubusercontent.com/49985975/180372289-9f650ee0-adc0-4706-9c4e-c9addf528e1d.png)
![image](https://user-images.githubusercontent.com/49985975/180372314-6bbcfd80-6749-4b96-bc05-3f6903dc010f.png)

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
