### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by Henrysilently** [HMUniversity/About#61]
Dear whom may concern,
Hello. I want to join Home University to lie flat!

Regards,
Henrysilently

**Comment by KevinZonda** [comment]
Hi @ Henrysilently,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University

**Comment by KevinZonda** [comment]
Hi @Henrysilently ,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
