### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by setobox** [HMUniversity/About#638]
Dear whom may concern,  
Hello. I want to join Home University to lie flat!

Check the college if you want to join it:
- [x] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- [ ] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

Regards,  
姬顶盒

**Comment by setobox** [comment]
I'm sorry I missed the email last time

**Comment by Cubik65536** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
