### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by xtexChooser** [HMUniversity/About#654]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！

如果你想加入一个特定学院请在此处勾选：

- - [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- - [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- - [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
xtex
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEQ9VexyhYBNHp/qr7l48udg2dsOsFAmOpnKoACgkQl48udg2d
sOvtYxAAujBRZrSpn0LQfszoWl7i0kYyc1SFhA7exxmkhSlLkYk9mpMiGpbV6iOy
bjeZx4VCYED9SwmWDIo9b1EGn6Bph2UmnUnqicFflMV+/MqMy+x0qy4EX1GmUz3l
xwlBO5FANe8Wh94ZIPQiIItPkEiR4fXtgWSBkFj8S+TcTtwsWbDbbDPilLANmtT+
cgVOZem9PPur5QjyYtN/IpT4wyrwC2HyFkQ46hebRW8rWlqN3wR5xRD2CjDKyw2r
1SmNJvdByhiuBf7laSfSfFcxmYVLHPL7EAc5xxs6EcPeay2yl5VJvjL3K94WetPP
chsC5VY/MQcynG5+PQVsgbbDrWrzvbID7c8YPyhCngJjLt6k/SEkagGmzTNWLejR
xAjnTS/0SwfDRWsyKr685JopjIRJL9YeTl5HzBZ9RBKtGYOKcH7LU2hBcZxhMJto
/QNs+R1o5GT3xiEq/JaOyIZlDCB1/Zi/IqdYK3x10OOKLS0s24AlBr8CyoXlU1oI
VSCd6WxZoxf4VhgAfjsNC41tLGIC6PxwTXKcXtJ6vBJ/Zd07HjJwoH8yqZGFjSWy
V3YVLO/kHB8f0ICEx2bpkRO3rhbWPUJtwQUpr1FLeGx5iKDp/xqVIE3fT5mOT1j3
aHMN71rEUsOuBsigvxP+/R1qW/MN027uLaWjOCzqqX6HfduhkSI=
=FC6n
-----END PGP SIGNATURE-----

-----BEGIN PGP PUBLIC KEY BLOCK-----
mQINBGAdEf4BEADUS2TVyWhmzbEYDvE3SORI+oWpIoPpsqPmRO7s4d9xarxKecpp
4watnYduvBXSSj4lMzHUqKW+10r2i2PYkrRZb6D9bVb2ZALiTmYzKmkfRwlFLQhp
yq3/sZ4YH7Vihe9NjmC+wOpA63dp4SRhNe2YYqgTTph6KYUrqsfZmS1xsGRCSHNT
SH9XsYld4Wko7W+X37nexEfkH/NUQcVbBC+N9sOGD1tep2B+t1l0uZr3Ds70hlQM
0LRpbBqqazzR1bs3XO9D1/+bqJ+aslqD6xVbJSLSFdAMa1SXljXpm4nmOmWSzJet
lNEUYkmeqA7tS70K0//e6HAFBn869AI623W+R0lyaqfc1iqJ4VReAZC3EKNIaQIk
1Hw6ZoUuIF1CIMbkBisVm4K92/FaIjTC77TqHgwb7ImfT+BsMgz+8bhgD3BwHnWT
BToob4Na9BgMNhERTJI+Rty3bmlKvqytLZS5tGW95cXPO9BGsVs8UqB2sEue6xj0
Tgr/NPOvMJoZH8Z6TSZTh7tEpXx+7y1kve0Vc4Ww1Iu1NXm77p2eWMFx0UFqIAer
LHVZGp4i9YlRKInVpilJ13IW37IkBSb4DtczK8EO4bfPPhmbJ/f9F10D+WUE9dnA
tGj13iHZ8oJnzoLKYth+5vw+oghSgJt/wWXipJxPqZWT0FW5SXcv0GRoHwARAQAB
tBx4dGV4Q2hvb3NlciA8emJ3eHRleEBxcS5jb20+iQJOBBMBCAA4FiEEQ9VexyhY
BNHp/qr7l48udg2dsOsFAmAdEf4CGwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AA
CgkQl48udg2dsOuOFxAAi7XjWgYrMm9fvvZfCwS8vm2p4IXvgbyvCfGmtyWx4vIw
0K3fO/00o7Aj5z9T/S4NYgw7BkolrEc1/mUECNeNwlEr2R/z7ZeR5uvL4pU1Up7R
rxfYV4+GOASsClbwHw22yAY1sW1G0EA965o8qyVq62KJdQ1wFNFovsiZXuoPsQG0
M9+Srz7YIYlbZc4+357iGbneM682nilxgKd6HX48F6ynl43Om6yMsupr4dS1ZCO1
9zjOUIDumyW/kYLY3Z1E3Kx7+y0dhPTrIhRyVQ4CmMHjAei87iiYrv3Z5oaBnqbw
m1PHitUfUO8u9hY8WXsKzGP/9p2GMO8qvTbPuCZ4/LomVWrRp7Z49V2vygWk0nes
H290HeLeXq7Et0ieUIHgvveu/vRCZyI2j+SK+cnTnemdKhNTF/w+KJDZkJH8UOLh
N3+eWohmkTx+DvT+4DbBt1ZFKxAygQ78vDTzNUKIr2ixjhRaFJzDj4skNbois+Dp
XpQU2gQkfRMjJQE8AiAGCTMtXngWHZ1eVBqzfe3gvBphe/jclIw5DI9zvLPHpr/O
rOjto45THU43qW5eiqC2Nh7lYUciUo62qFvLrLOlmWKpgm3dmyssf6c9LTDxv/V0
3YWuvweiZ5+vTHCAsVbhboV60inFG/qh04pgjuCZH/Mosqp4pkpA60PpyEHLTem0
H3h0ZXhDaG9vc2VyIDxteXpid0BvdXRsb29rLmNvbT6JAlEEEwEIADsWIQRD1V7H
KFgE0en+qvuXjy52DZ2w6wUCY1xTCQIbAwULCQgHAgIiAgYVCgkICwIEFgIDAQIe
BwIXgAAKCRCXjy52DZ2w601jD/4/OOfmtEFZvb91QMZpKwZaxhTr8tSgAimJsIxP
aMWQWAqY03E/DmAPfjWlvRbmqIz7h8BG4DFjhoViVctkI2SiB6MZd6+gw9oJ2Uz3
uDATmd+Ie9dI/qWXqvY/ERX0Op7Nr57dBtKmbjPXgm1nTBn7oNESYyMkXm+XvWap
3qFsNgjeenp8hGsBZ2IBMNrkOAplSIYnVUfWG4iFz/9zK4Ty+L5p5u7CTAfSDVmW
R3aFLX/fWGbHooqphUyL4hlP4P7vjJy8gIejrCQKKGkq4JwdT3hdphBR/pU+1DAU
u3FEnD6A5+D2KFrjosUcDQjpYikRxWRvEaoNnwDA2UDEhnEzdpj/xbcJC0Tv/Ec7
H/uZ7YJ4c/130x8R60PuP/JHFrifbyAPO1HdWdqZASOgVPxNHheMLSP7TNAirFYH
GftP9ua3Gb3SSSGyXqQDEx9ovKY8mYtmZqXOzRluifmqEU2gfHeKrcNrMMRU5JUP
Pm4p0Es+xw9TPxnsMD2e+oXfUF807lCUHtYXkgLj2i2nZNWFQpdwiOfh1OF9eHmH
VZM/Ga+ryuCWH0KGSFV7ANoDvjD+PeSybCZNhV02dRrjOyzSeefd3FjTHcb/Qcuz
WBAD17ctT6m8lrpWvDzHnq5ou5Y2VOIm/xECR1tPCUiosMNF41jNaEL0P7o/T+mD
bEVyurQieHRleENob29zZXIgPHh0ZXhjaG9vc2VyQGR1Y2suY29tPokCUQQTAQgA
OxYhBEPVXscoWATR6f6q+5ePLnYNnbDrBQJjXFMWAhsDBQsJCAcCAiICBhUKCQgL
AgQWAgMBAh4HAheAAAoJEJePLnYNnbDrnS0P/3vR7w9dkRoSyubJNmJCxgJFdBIg
4O1zKItZTg9nz4Fm3ETk6vUC9Yw9XlIBoV2t3zEQKbGJTmSYk477BPDWVOYFqNwb
RYRkKGRddTnW7iTArJlFKE6Ih5Ny5lNIS5qEkh/B7Z9+8RuVCT+umbGY4QEHOXTm
gymLKLFNKZwLbDxHQZkisEc5wRgR5RCv4qHAoWCY7lDS7ItQTzxMYfld8bTh0M3J
Xvd5TEZnOMAg0YUHRUUF3vFGo+B2nxL0avn1RSQ3nawRlvPWaU8nfGQWewcX7dIE
YfGrBAsnYtcEuHo7+aV5OVn4n/FuOf7SlQ5XAtMnU6l9WnpQTqX9jzIGfSHte1YQ
K33IkS2+pc/v/WrMBIoFgJ22A05Ya7Kq9PMaHIwhVxcHHORxCCrCv8iuHkQ2XnBR
RVhafWzy6mvKL+jtiucewuQYuHtEbAiwutaKnylq1e6DRolWZalGcAG27vvdsWlA
/3nVZ+gt7lWORo1JGQ9I8abeUtpApVfF6YY4frHz2a2FWvy02R6Dkte5QSSwsWbI
ekK9T034eOQOEaWHBD+BmZ3/wkwH0+EbDXYXcSC+eMuvluRaVuWoc5+AXMkLHjX4
bz0yxZeKOYzn5yx1DtqaXEcmWJEHHssusX5UHvPd31aUMTI+M6YTKjvy0vN8SFsn
9x7dlFngmwevTykLuQINBGAdEf4BEADDdKbwFvAI+pyJ652dEh0b9nZ15cbJq+dW
Xj0TNzdhURrtgftJvYG5xIv5CmOkcsIfSzcVrwwJJcEwHF5hFVngcu/qAM9aZCmN
Q2f5+t8Hu3zo7JAORTIuiEWu3XvVHzpM7OTA2ly49EAhUoiQfWxq1PXPQ5aPzOPc
XIvbldZWx7hZ4A4/aFwBwhDVUlTUTeKk+JH/1+mT3ybRraio8KUJe8ZKa3XskgGU
TQUs0k2P1Ee0K3qpu3RBki6n/Ugr/b/z0KIJW6h7uaksixY0cBo3qI5uW4dssVWa
eBWljO7Zx69LDF7Ran/nv4JCvE3UdikU3elUcWUC/7sOT/ZWJVHYa+FAc/+UpfYe
YMApr3UTzEi3QUg9UGg4FzMa5p223NQR3tztWf66ETf297/da/iaIGHZnKG+b5oZ
3aJVA33cGMBfI34lVea6qtCPD5+TPdGZq6cH5k08MjE0Za+NqHTLshwb8lvEGs77
cKrqZEq5qtj91u29sbKOydTV57zt/LlcaegO8ryL7poxro5qryo2/Zb5HrqK8oaP
TRLGq20ohKzWhKIzcBMl5mvf7Xf18HLbdspGCNrOn0XEGrJ8LCoQFPtjyLO2TWIM
m6VI8azZ8myDkXye2GfZvWhglkAL9cf4xRruJt6UL+5NWOfpwsRp+4/swk3Xx1R7
AXyUcsF2gwARAQABiQI1BBgBCAAgFiEEQ9VexyhYBNHp/qr7l48udg2dsOsFAmAd
Ef4CGwwACgkQl48udg2dsOv/WQ/3awt6AG+2bthGkTpqJrktWHRkbfRlf2MhmZGz
I0xZ/SkOFcBiNlw6BllbAxda+bKOuIZ/SK8AX0hOJXSGTBaXak4fB5P5jDYKgONl
Ru/BRGHNVfz8cnxCRQbAQ138hIxP5HY3i66GqGUjjvHaUMBrWrg29aa15XRYQFpl
6ieT9yDmlu9J84djgeAxJiVTXK/YU+kw+EEeV65c1nrnhsyt1LjwHxF0XlZrm5z9
5o7Jpe3d2YTmc2Lr1LDJgjUxCU9QM4krrLGeLha1n8CHnk4Nruysjj0q8+SP8OwY
YG3QNEyQu9tZc1kFAvsZbRpsvZTJCNrGQNhIOP4TZNNiUIidSCg3jOAe/Zaw88CJ
5KlfXRMkAdK2lUNyN5gNmo7hon1YlH1XvHA6xkRWnPaNlWf1R+r4co/Z6/V8q34h
39bNSPi8IZmuy4IbsXmnCXrDp5fKMEdpRT1SaYw+pJCV3p2IF8BKE0PhIm8zlxEB
tIaix0cPQxMR8y5aUcKbuK5uBOVm1u+JPc1AjAWX/cxRPGH3eOYKVXugqwa1Ytmz
pE2bwXDeuElFW1trf+qMIpC8NZy/677QyGFoQEqxuod+95yjG8BKItW4utP/2laQ
vX8ESmoEQDoliJeO9eW1h8dRNPYB2gEwNVraV6s7mG2QWE8b0tLJ7y0szvxpI71j
Voq9HA==
=ECS0
-----END PGP PUBLIC KEY BLOCK-----

**Comment by Cubik65536** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
