### ISSUE TITLE
Use GitHub Action & Issue labels for sending admission letters

### ISSUE THREAD

**Issue by Cubik65536** [HMUniversity/About#666]
Should we use GitHub Action & Issue labels for sending admission letters? In that case, all we have to do is add a label to the issue and we don't have to copy & paste for each application.

**Comment by KevinZonda** [comment]
Cant do cause I am 依托大便, not able to do the ci

Pr welcome

**Comment by Cubik65536** [comment]
> Cant do cause I am 依托答辩, not able to do the ci
> 
> Pr welcome

Added in PR #667
