### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by Tigger2333** [HMUniversity/About#704]
Dear whom may concern,  
Hello. I want to join Home University to lie flat!

Check the college if you want to join it:
- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- [> ] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

Regards,  
<Tigger2333>

**Comment by Cubik65536** [comment]
Duplicate #702
