### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by huccct** [HMUniversity/About#776]
Dear whom may concern,  
Hello. I want to join Home University to lie flat!

Check the college if you want to join it:
- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

Regards,  
huccct

**Comment by huccct** [comment]
absolutely

**Comment by huccct** [comment]
So what can I do for our organization

**Comment by LaoshuBaby** [comment]
> So what can I do for our organization

同学：
　　你好！
　　会问出这样的问题，说明你心态过于端正，仍然需要继续进修校本特色课程《躺平学原理》、《摸鱼学导论》。

祝好！

**Comment by huccct** [comment]
hhh got it
