### ISSUE TITLE
Location should not be United Kingdom?

### ISSUE THREAD

**Issue by HtwoO** [HMUniversity/About#781]
Location of the organization should not be in the UK, right?
It should be a logic location, something like `::1`, "[CONCRETE](https://en.wikipedia.org/wiki/Concrete_Mathematics) entropy", "Meow" or `∀`

**Comment by KevinZonda** [comment]
HMU has no specific location, but the first college of HMU (St. Chi College, formerly known as HMU) was found in Sussex, UK.
