### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by HUA428571** [HMUniversity/About#812]
Dear whom may concern,  
Hello. I want to join Home University to lie flat!

Check the college if you want to join it:
- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

Regards,  
HUA428571

**Comment by NneurotransmitterR** [comment]
Welcome！

**Comment by KevinZonda** [comment]
Welcome! /accept
