### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by silenty4ng** [HMUniversity/About#815]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！

如果你想加入一个特定学院请在此处勾选：

- [x] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [x] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
奚玉帆

**Comment by silenty4ng** [comment]
@cw1997 老师，走个后门。

**Comment by LaoshuBaby** [comment]
尊敬的 @silenty4ng 

感谢您与我们联系并表达您对加入家里蹲大学的兴趣。我们理解学生们在寻求入学过程中可能会寻求不同方式以增加录取的可能。

然而，我必须强调，我们学校重视公平和透明的招生流程。我们承诺提供平等的机会给所有申请者，确保每一位同学都通过相同的评审标准被公正对待。因此，我们无法考虑任何特殊途径或个人推荐作为录取决策的一部分。

我们鼓励所有学生通过正规申请流程展示他们的能力和潜力，我们将基于申请材料中展现的资质对每个候选人进行评估。

请理解这一立场，它不仅体现了我们的招生原则，也为了确保每位申请者的利益。

再次感谢您的理解和对鄙校的兴趣。

Best wishes

家里蹲大学 教务处

**Comment by silenty4ng** [comment]
好的老师，我会继续努力的。

**Comment by LaoshuBaby** [comment]
(其实上面那段是AI写的)

家里蹲大学本身就具有一定行为艺术性质，按说直接摆烂等着accept就可以，但是你居然这么积极的询问录取事宜，那你这就与本校摸鱼划水的精神相违背了啊（挠头

**Comment by silenty4ng** [comment]
这不走后门就很摆烂吗（挠头

**Comment by tsurumi-yizhou** [comment]
越摆烂越烂，越烂越走捷径，越走捷径越不摆烂，所以越摆烂越不摆烂

**Comment by KevinZonda** [comment]
Transparency of Admission is crucial. I respect all decisions made by Committee’s member of the HMU.

**Comment by Cubik65536** [comment]
> (其实上面那段是AI写的)
> 
> 家里蹲大学本身就具有一定行为艺术性质，按说直接摆烂等着accept就可以，但是你居然这么积极的询问录取事宜，那你这就与本校摸鱼划水的精神相违背了啊（挠头

现在就是按心情 accept，收几个也是随机的，等着就好
