### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by silenty4ng** [HMUniversity/About#816]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！

如果你想加入一个特定学院请在此处勾选：

- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
Silent YANG

**Comment by KevinZonda** [comment]
Welcome, morty.

**Comment by KevinZonda** [comment]
Kinna found sth interest, Google Translate translates the home to the loo lol
<img width="985" alt="image" src="https://github.com/HMUniversity/About/assets/33132228/d4c591d2-849c-4216-a73c-d17c8a93a1f6">
