### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by dqhl76** [HMUniversity/About#823]
Dear whom may concern,  
Hello. I want to join Home University to lie flat!

Check the college if you want to join it:
- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

Regards,  
dqhl76

**Comment by hudsonhu** [comment]
Sorry to inform that you have been rejected.

**Comment by dqhl76** [comment]
Firmly Accept.

**Comment by LaoshuBaby** [comment]
Note: Users who impersonate the identity of the Academic Affairs Office to spread false admission or rejection messages have been blocked.
