### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by Paper-Dragon** [HMUniversity/About#859]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！

如果你想加入一个特定学院请在此处勾选：

- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
Paper-Dragon

**Comment by Paper-Dragon** [comment]
没有收到加入组织的邀请哦！可否重发下

**Comment by Paper-Dragon** [comment]
@KevinZonda

**Comment by KevinZonda** [comment]
Sent
