### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by LofiSu** [HMUniversity/About#907]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！

如果你想加入一个特定学院请在此处勾选：
（我不太懂这些学院有什么区分可以给我讲一下吗？另外问问有qq或者微信群吗）

- [ √] [Kindergarten College](https://github.com/orgs/HMUniversity/teams/kindergarten-college)
- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
<LofiSu>

**Comment by LofiSu** [comment]
在哪里确认啊，没有邮件啊

**Comment by KevinZonda** [comment]
<img width="269" alt="image" src="https://github.com/user-attachments/assets/233efac4-f08d-4f02-930c-5f155e006c38">
