### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by stbanana** [HMUniversity/About#909]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！

如果你想加入一个特定学院请在此处勾选：

- [ ] [Kindergarten College](https://github.com/orgs/HMUniversity/teams/kindergarten-college)
- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)
- [ ] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)
- [ ] [ZWB College](https://github.com/orgs/HMUniversity/teams/zwb-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
<yono>

**Comment by stbanana** [comment]
😤建议贵校速速安排本人的入学事宜，否则本人躺在门口不走了！

**Comment by KevinZonda** [comment]
保卫科！保卫科！快请这位秀儿速速入学！

**Comment by LaoshuBaby** [comment]
晚了！保卫科已经给这位同学架出去了！
(^o^)／

**Comment by xtexChooser** [comment]
@LaoshuBaby 草，好可怕

**Comment by yzqzss** [comment]
谢谢保卫科的老鼠门卫，是您，保卫了家里蹲大学的家里蹲的家里蹲生活。

敬礼！

**Comment by stbanana** [comment]
我在校食堂吃过饭！你们不能这样对我！我要见校长！我要上访！我要上访

**Comment by KevinZonda** [comment]
入学入学！
