### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by AHpxChina** [HMUniversity/About#93]
Dear whom may concern,
Hello. I want to join Home University to lie flat!

Silence, Capitalist, I do not want to join involution anymore, I just want to be happy

Regards,
AHpxChina

**Comment by KevinZonda** [comment]
Hi @AHpxChina,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Home University
